apiVersion: v1
kind: Service
metadata:
  name: common-node-js-service
spec:
  selector:
    app: common-node-js
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
